/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package du_an_mau.Views;

import du_an_mau.DomainModels.DongSP;
import du_an_mau.DomainModels.MauSac;
import du_an_mau.DomainModels.NSX;
import du_an_mau.DomainModels.SanPham;
import du_an_mau.Service.ChiTietSanPhamService;
import du_an_mau.Service.DongSPService;
import du_an_mau.Service.MauSacService;
import du_an_mau.Service.NSXService;
import du_an_mau.Service.SanPhamService;
import du_an_mau.Service.impl.ChiTietSanPhamimpl;
import du_an_mau.Service.impl.DongSPServiceimpl;
import du_an_mau.Service.impl.MauSacServiceimpl;
import du_an_mau.Service.impl.NSXServiceimpl;
import du_an_mau.Service.impl.SanPhamServiceimpl;
import du_an_mau.ViewModels.ChiTietSanPhamViewModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import duanmau.model.ChiTietSanPham;

/**
 *
 * @author ASUS
 */
public class ChiTietSanPhamUI extends javax.swing.JFrame {

    private DefaultComboBoxModel defaultComboBoxModel;

    private DefaultTableModel defaultTableModel;
    private DongSPService dongSPService = new DongSPServiceimpl();
    private NSXService nSXService = new NSXServiceimpl();
    private MauSacService mauSacService = new MauSacServiceimpl();
    private SanPhamService sanPhamService = new SanPhamServiceimpl();
    private ChiTietSanPhamService chiTietSanPhamService = new ChiTietSanPhamimpl();
//    private DefaultComboBoxModel dcbbNsx;

    /**
     * Creates new form ChiTietSanPham
     */
    public ChiTietSanPhamUI() {
        initComponents();
        loadcbbDongsp(dongSPService.getList());
        loadcbbNSX(nSXService.getList());
        loadcbbMauSac(mauSacService.getList());
        loadcbbSP(chiTietSanPhamService.getListcbb());

        loadData(chiTietSanPhamService.getList());

    }

    private void loadcbbDongsp(ArrayList<DongSP> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbdongsp.getModel();

        for (DongSP dongSP : list) {
            defaultComboBoxModel.addElement(dongSP);
        }
    }

    private void loadcbbNSX(ArrayList<NSX> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbnsx.getModel();

        for (NSX str : list) {
            defaultComboBoxModel.addElement(str);
        }
    }

    private void loadcbbMauSac(ArrayList<MauSac> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbms.getModel();

        for (MauSac str : list) {
            defaultComboBoxModel.addElement(str);
        }
    }

    private void loadcbbSP(ArrayList<SanPham> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbmasp.getModel();

        for (SanPham str : list) {
            defaultComboBoxModel.addElement(str);

        }
    }

    public void loadData(ArrayList<ChiTietSanPhamViewModel> list) {
        defaultTableModel = (DefaultTableModel) tblsp.getModel();
        defaultTableModel.setRowCount(0);

        for (ChiTietSanPhamViewModel ctsp : list) {
            defaultTableModel.addRow(new Object[]{
                defaultTableModel.getRowCount() + 1, ctsp.getIdsp().getMasp(), ctsp.getIdsp().getTensp(), ctsp.getNamBH(), ctsp.getMoTa(),
                ctsp.getSoLuongTon(), ctsp.getGiaNhap(), ctsp.getGiaBan(), ctsp.getId()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbnsx = new javax.swing.JComboBox<>();
        cbbdongsp = new javax.swing.JComboBox<>();
        cbbms = new javax.swing.JComboBox<>();
        txtnambh = new javax.swing.JTextField();
        txtmt = new javax.swing.JTextField();
        txtsl = new javax.swing.JTextField();
        txtgianhap = new javax.swing.JTextField();
        txtban = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        cbbmasp = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chi Tiết Sản Phẩm");

        jLabel2.setText("Sản Phẩm");

        jLabel3.setText("Tên Dòng SP");

        jLabel4.setText("Tên NSX");

        jLabel5.setText("Tên Màu Sắc");

        jLabel6.setText("Năm BH");

        jLabel7.setText("Số Lượng Tồn");

        jLabel8.setText("Mô Tả");

        jLabel9.setText("Giá nhập");

        jLabel10.setText("Giá bán");

        cbbdongsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbdongspActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel12.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnthem)
                        .addGap(73, 73, 73)
                        .addComponent(btnsua)
                        .addGap(114, 114, 114)
                        .addComponent(btnxoa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnambh, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(txtsl)
                                .addComponent(txtban))
                            .addComponent(cbbmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmt)
                                .addComponent(cbbdongsp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbbms, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbnsx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbnsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbbmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnambh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbdongsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "tên sp", "năm bh", "mô tả", "sl tồn", "giá nhập", "giá bán", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblsp);
        if (tblsp.getColumnModel().getColumnCount() > 0) {
            tblsp.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspMouseClicked
        // TODO add your handling code here:
        int row = tblsp.getSelectedRow();
        if (row == -1) {
            return;
        }
        String id = tblsp.getValueAt(row, 8).toString();
        String ma = tblsp.getValueAt(row, 1).toString();
        String ten = tblsp.getValueAt(row, 2).toString();
        String nam = tblsp.getValueAt(row, 3).toString();
        String mt = tblsp.getValueAt(row, 4).toString();
        String sl = tblsp.getValueAt(row, 5).toString();
        String nhap = tblsp.getValueAt(row, 6).toString();
        String ban = tblsp.getValueAt(row, 7).toString();

        defaultComboBoxModel = (DefaultComboBoxModel) cbbnsx.getModel();
        defaultComboBoxModel.setSelectedItem(chiTietSanPhamService.getList().get(row).getIdnsx());

        defaultComboBoxModel = (DefaultComboBoxModel) cbbdongsp.getModel();
        defaultComboBoxModel.setSelectedItem(chiTietSanPhamService.getList().get(row).getIddongsp());

        defaultComboBoxModel = (DefaultComboBoxModel) cbbms.getModel();
        defaultComboBoxModel.setSelectedItem(chiTietSanPhamService.getList().get(row).getIdms());

        defaultComboBoxModel = (DefaultComboBoxModel) cbbmasp.getModel();
        defaultComboBoxModel.setSelectedItem(chiTietSanPhamService.getList().get(row).getIdsp());

        lblid.setText(id);

        txtmt.setText(mt);
        txtnambh.setText(nam);
        txtsl.setText(sl);
        txtban.setText(ban);
        txtgianhap.setText(nhap);


    }//GEN-LAST:event_tblspMouseClicked

    private void cbbdongspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbdongspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbdongspActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        ChiTietSanPhamViewModel ctsp = new ChiTietSanPhamViewModel();

        SanPham idsp = (SanPham) cbbmasp.getSelectedItem();
//        SanPham ten = (SanPham) cbbmasp.getSelectedItem();

        DongSP dsp = (DongSP) cbbdongsp.getSelectedItem();

        MauSac ms = (MauSac) cbbms.getSelectedItem();

        NSX nsx = (NSX) cbbnsx.getSelectedItem();

        String nambh = txtnambh.getText();
        String slt = txtsl.getText();
        String mt = txtmt.getText();
        String nhap = txtgianhap.getText();
        String ban = txtban.getText();

        if (String.valueOf(nambh).isEmpty() || String.valueOf(slt).isEmpty() || mt.isEmpty() || nhap.isEmpty() || ban.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được bổ trống");
            return;
        }

        try {
            Double.parseDouble(nhap);
            Double.parseDouble(ban);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lương phải là số");
            return;
        }
        if (Double.parseDouble(nhap) == 0 || Double.parseDouble(ban) == 0 || Integer.parseInt(slt) == 0) {
            JOptionPane.showMessageDialog(this, "Lương không được bằng 0");
            return;
        } else if (Double.parseDouble(nhap) < 0 || Double.parseDouble(ban) < 0 || Integer.parseInt(slt) < 0) {
            JOptionPane.showMessageDialog(this, " không được âm");
            return;
        }

        try {
            Integer.parseInt(nambh);
            Integer.parseInt(slt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "phải là số nguyên");
            return;
        }

        ctsp.setIdms(ms);
        ctsp.setIdnsx(nsx);
        ctsp.setIdsp(idsp);
        ctsp.setIddongsp(dsp);
        ctsp.setMoTa(mt);
        ctsp.setNamBH(Integer.parseInt(nambh));
        ctsp.setSoLuongTon(Integer.parseInt(slt));
        ctsp.setGiaBan(Double.parseDouble(ban));
        ctsp.setGiaNhap(Double.parseDouble(nhap));

        if (chiTietSanPhamService.insert(ctsp)) {
            JOptionPane.showMessageDialog(this, "ok");
            loadData(chiTietSanPhamService.getList());
        } else {
            JOptionPane.showMessageDialog(this, "No");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        ChiTietSanPhamViewModel ctsp = new ChiTietSanPhamViewModel();

        String id = lblid.getText();

        SanPham idsp = (SanPham) cbbmasp.getSelectedItem();
//        SanPham ten = (SanPham) cbbmasp.getSelectedItem();

        DongSP dsp = (DongSP) cbbdongsp.getSelectedItem();

        MauSac ms = (MauSac) cbbms.getSelectedItem();

        NSX nsx = (NSX) cbbnsx.getSelectedItem();

        String nambh = txtnambh.getText();
        String slt = txtsl.getText();
        String mt = txtmt.getText();
        String nhap = txtgianhap.getText();
        String ban = txtban.getText();

        if (String.valueOf(nambh).isEmpty() || String.valueOf(slt).isEmpty() || mt.isEmpty() || nhap.isEmpty() || ban.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được bổ trống");
            return;
        }

        try {
            Double.parseDouble(nhap);
            Double.parseDouble(ban);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lương phải là số");
            return;
        }
        if (Double.parseDouble(nhap) == 0 || Double.parseDouble(ban) == 0 || Integer.parseInt(slt) == 0) {
            JOptionPane.showMessageDialog(this, "Lương không được bằng 0");
            return;
        } else if (Double.parseDouble(nhap) < 0 || Double.parseDouble(ban) < 0 || Integer.parseInt(slt) < 0) {
            JOptionPane.showMessageDialog(this, " không được âm");
            return;
        }
        try {
            Integer.parseInt(nambh);
            Integer.parseInt(slt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "phải là số nguyên");
            return;
        }

        ctsp.setIdms(ms);
        ctsp.setIdnsx(nsx);
        ctsp.setIdsp(idsp);
        ctsp.setIddongsp(dsp);
        ctsp.setMoTa(mt);
        ctsp.setNamBH(Integer.parseInt(nambh));
        ctsp.setSoLuongTon(Integer.parseInt(slt));
        ctsp.setGiaBan(Double.parseDouble(ban));
        ctsp.setGiaNhap(Double.parseDouble(nhap));
        ctsp.setId(id);

        if (chiTietSanPhamService.update(id, ctsp)) {
            JOptionPane.showMessageDialog(this, "ok");
            loadData(chiTietSanPhamService.getList());
        } else {
            JOptionPane.showMessageDialog(this, "No");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String id = lblid.getText();

        if (chiTietSanPhamService.delete(id)) {
            JOptionPane.showMessageDialog(this, "ok");
            loadData(chiTietSanPhamService.getList());
        } else {
            JOptionPane.showMessageDialog(this, "No");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietSanPhamUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbbdongsp;
    private javax.swing.JComboBox<String> cbbmasp;
    private javax.swing.JComboBox<String> cbbms;
    private javax.swing.JComboBox<String> cbbnsx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblid;
    private javax.swing.JTable tblsp;
    private javax.swing.JTextField txtban;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtmt;
    private javax.swing.JTextField txtnambh;
    private javax.swing.JTextField txtsl;
    // End of variables declaration//GEN-END:variables
}
