/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package du_an_mau.Views;

import du_an_mau.DomainModels.ChucVu;
import du_an_mau.DomainModels.CuaHang;
import du_an_mau.Service.ChucVuService;
import du_an_mau.Service.CuaHangService;
import du_an_mau.Service.NhanVienService;
import du_an_mau.Service.impl.ChucVuServiceimpl;
import du_an_mau.Service.impl.CuaHangServiceimpl;
import du_an_mau.Service.impl.NhanVienServiceimpl;
import du_an_mau.ViewModels.NhanVienViewModels;
import java.util.ArrayList;
import java.sql.Date;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class NhanVienView extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienView
     */
    private DefaultTableModel defaultTableModel;
    private DefaultComboBoxModel defaultComboBoxModel;
    private NhanVienService nhanVienService = new NhanVienServiceimpl();
    private CuaHangService cuaHangService = new CuaHangServiceimpl();
    private ChucVuService chucVuService = new ChucVuServiceimpl();

    public NhanVienView() {
        initComponents();
        loaddcbbCH(cuaHangService.getList());
        loaddcbbCv(chucVuService.getList());
        loaddcbbtt();
        loaddata(nhanVienService.getList());
    }

    public void loaddcbbCH(ArrayList<CuaHang> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbch.getModel();

        for (CuaHang cuaHang : list) {
            defaultComboBoxModel.addElement(cuaHang);
        }
    }

    public void loaddcbbCv(ArrayList<ChucVu> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbcv.getModel();

        for (ChucVu cv : list) {
            defaultComboBoxModel.addElement(cv);
        }
    }

    public void loaddcbbtt() {
        ArrayList<String> list1 = new ArrayList<>();
        defaultComboBoxModel = (DefaultComboBoxModel) cbbtt.getModel();
        list1.add("Nghỉ việc");
        list1.add("Còn làm");

        for (String s : list1) {
            defaultComboBoxModel.addElement(s);
        }
    }

    public void loaddata(ArrayList<NhanVienViewModels> list) {
        defaultTableModel = (DefaultTableModel) tblnv.getModel();
        defaultTableModel.setRowCount(0);

        for (NhanVienViewModels nv : list) {
            defaultTableModel.addRow(new Object[]{
                defaultTableModel.getRowCount() + 1, nv.getManv(), nv.getTennv(),
                nv.getGt(), nv.getNs(), nv.getDiachi(), nv.getSdt(), nv.getMk(),
                nv.getTt() == 0 ? "Còn làm" : "Nghỉ việc", nv.getId()
            }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        txtns = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtmk = new javax.swing.JTextField();
        cbbcv = new javax.swing.JComboBox<>();
        cbbch = new javax.swing.JComboBox<>();
        cbbtt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        jLabel2.setText("Mã");

        jLabel3.setText("Tên");

        jLabel4.setText("GT");

        jLabel5.setText("NS");

        jLabel6.setText("Địa chỉ");

        jLabel7.setText("SĐT");

        jLabel8.setText("Mật Khẩu");

        jLabel9.setText("Chức vụ");

        jLabel10.setText("Cửa hàng");

        jLabel11.setText("TT");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdonam);
        rdonam.setText("Nam");

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem))
                .addGap(86, 86, 86)
                .addComponent(btnsua)
                .addGap(73, 73, 73)
                .addComponent(btnxoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdonam)
                                .addGap(30, 30, 30)
                                .addComponent(rdonu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbcv, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbtt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(rdonam)
                    .addComponent(rdonu)
                    .addComponent(cbbcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbbtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa))
                .addGap(39, 39, 39))
        );

        tblnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "tên", "gt", "ngày sinh", "địa chỉ", "sđt", "mật khẩu", "Tình trạng", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        NhanVienViewModels n = new NhanVienViewModels();
        String ma = txtma.getText();
        String ten = txtten.getText();

        String ngaySinh = txtns.getText();
        String sdt = txtsdt.getText();
        String diaChi = txtdiachi.getText();
        String mk = txtmk.getText();
        ChucVu cv = (ChucVu) cbbcv.getSelectedItem();
        CuaHang ch = (CuaHang) cbbch.getSelectedItem();

        if (ma.isEmpty() | ten.isEmpty() | ngaySinh.isEmpty() | sdt.isEmpty() | diaChi.isEmpty() | mk.isEmpty()) {
            JOptionPane.showMessageDialog(this, "K dc de trong thong tin");
            return;
        }

        for (int i = 0; i < sdt.length(); i++) {
            if (!Character.isDigit(sdt.charAt(i))) {
                JOptionPane.showMessageDialog(this, "SDT phai la so");
                return;
            }
        }
        Pattern paternDate = Pattern.compile("\\d{2}[-|/]\\d{2}[-|/]\\d{4}");
        paternDate = Pattern.compile("^\\d{4}[-|/]\\d{2}[-|/]\\d{2}$");
        if (paternDate.matcher(txtns.getText()).matches() == true) {
            JOptionPane.showMessageDialog(this, "dung dinh dang ngay sinh");
        }
        if (paternDate.matcher(txtns.getText()).matches() == false) {
            JOptionPane.showMessageDialog(this, "sai dinh dang ngay sinh");
            return;
        }
        Date d = Date.valueOf(txtns.getText());

        cv.setId(cv.getId());
        n.setIdcv(cv);

        ch.setId(ch.getId());
        n.setIdch(ch);

        n.setManv(ma);
        n.setTennv(ten);
        ;
        if (rdonam.isSelected()) {
            n.setGt("Nam");
        } else {
            n.setGt("Nữ");
        }
        n.setSdt(sdt);
        n.setDiachi(diaChi);
        n.setMk(mk);
        n.setNs(d);
        if (cbbtt.getSelectedItem().equals("Còn làm")) {
            n.setTt(1);
        } else {
            n.setTt(0);
        }
        if (nhanVienService.insert(n)) {
            JOptionPane.showMessageDialog(this, "Thêm ok");
            loaddata(nhanVienService.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Thêm No");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        NhanVienViewModels n = new NhanVienViewModels();
        String id = txtid.getText();
        String ma = txtma.getText();
        String ten = txtten.getText();

        String ngaySinh = txtns.getText();
        String sdt = txtsdt.getText();
        String diaChi = txtdiachi.getText();
        String mk = txtmk.getText();
        ChucVu cv = (ChucVu) cbbcv.getSelectedItem();
        CuaHang ch = (CuaHang) cbbch.getSelectedItem();

        if (ma.isEmpty() | ten.isEmpty() | ngaySinh.isEmpty() | sdt.isEmpty() | diaChi.isEmpty() | mk.isEmpty()) {
            JOptionPane.showMessageDialog(this, "K dc de trong thong tin");
            return;
        }

        for (int i = 0; i < sdt.length(); i++) {
            if (!Character.isDigit(sdt.charAt(i))) {
                JOptionPane.showMessageDialog(this, "SDT phai la so");
                return;
            }
        }
        Pattern paternDate = Pattern.compile("\\d{2}[-|/]\\d{2}[-|/]\\d{4}");
        paternDate = Pattern.compile("^\\d{4}[-|/]\\d{2}[-|/]\\d{2}$");
        if (paternDate.matcher(txtns.getText()).matches() == true) {
            JOptionPane.showMessageDialog(this, "dung dinh dang ngay sinh");
        }
        if (paternDate.matcher(txtns.getText()).matches() == false) {
            JOptionPane.showMessageDialog(this, "sai dinh dang ngay sinh");
            return;
        }
        Date d = Date.valueOf(txtns.getText());

        cv.setId(cv.getId());
        n.setIdcv(cv);

        ch.setId(ch.getId());
        n.setIdch(ch);

        n.setManv(ma);
        n.setTennv(ten);
        n.setId(id);
        ;
        if (rdonam.isSelected()) {
            n.setGt("Nam");
        } else {
            n.setGt("Nữ");
        }
        n.setSdt(sdt);
        n.setDiachi(diaChi);
        n.setMk(mk);
        n.setNs(d);
        if (cbbtt.getSelectedItem().equals("Còn làm")) {
            n.setTt(1);
        } else {
            n.setTt(0);
        }
        if (nhanVienService.update(id, n)) {
            JOptionPane.showMessageDialog(this, "Sửa ok");
            loaddata(nhanVienService.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Sửa No");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String id = txtid.getText();

        if (nhanVienService.delete(id)) {
            JOptionPane.showMessageDialog(this, "Xóa ok");
            loaddata(nhanVienService.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Xóa No");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnvMouseClicked
        // TODO add your handling code here:
        int row =tblnv.getSelectedRow();
        if(row ==-1){
            return;
        }
        
        String id =tblnv.getValueAt(row, 9).toString();
        String ma =tblnv.getValueAt(row, 1).toString();
        String ten =tblnv.getValueAt(row, 2).toString();
        String gt =tblnv.getValueAt(row, 3).toString();
        String ns =tblnv.getValueAt(row, 4).toString();
        String diachi =tblnv.getValueAt(row, 5).toString();
        String sdt =tblnv.getValueAt(row, 6).toString();
        String mk =tblnv.getValueAt(row, 7).toString();
        String tt =tblnv.getValueAt(row, 8).toString();
        
        defaultComboBoxModel=(DefaultComboBoxModel) cbbch.getModel();
        defaultComboBoxModel.setSelectedItem(nhanVienService.getList().get(row).getIdch());
        
        defaultComboBoxModel=(DefaultComboBoxModel) cbbcv.getModel();
        defaultComboBoxModel.setSelectedItem(nhanVienService.getList().get(row).getIdcv());
        
        txtid.setText(id);
        txtma.setText(ma);
        txtten.setText(ten);
        txtsdt.setText(sdt);
        txtmk.setText(mk);
        txtns.setText(ns);
        txtdiachi.setText(diachi);
        
        cbbtt.setSelectedItem(tt);
        
        if(gt.equalsIgnoreCase("Nam")){
            rdonam.setSelected(true);
        }else{
            rdonu.setSelected(true);
        }
        
                
       
        
    }//GEN-LAST:event_tblnvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbch;
    private javax.swing.JComboBox<String> cbbcv;
    private javax.swing.JComboBox<String> cbbtt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tblnv;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtns;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables

}
